/mlserver/logs/error.log {
  rotate 100
  weekly
  compress
  missingok
  notifempty
  postrotate
    /bin/kill -USR1 `cat /usr/local/openresty/nginx/logs/nginx.pid 2>/dev/null` 2>/dev/null || true
  endscript
}

/mlserver/logs/access_search.log {
  rotate 100
  daily
  compress
  missingok
  notifempty
  postrotate
    /bin/kill -USR1 `cat /usr/local/openresty/nginx/logs/nginx.pid 2>/dev/null` 2>/dev/null || true
  endscript
}


/mlserver/logs/access_viewlyrics.log {
  rotate 100
  daily
  compress
  missingok
  notifempty
  postrotate
    /bin/kill -USR1 `cat /usr/local/openresty/nginx/logs/nginx.pid 2>/dev/null` 2>/dev/null || true
  endscript
}

/mlserver/logs/access_crintsoft.log {
  rotate 100
  daily
  compress
  missingok
  notifempty
  postrotate
    /bin/kill -USR1 `cat /usr/local/openresty/nginx/logs/nginx.pid 2>/dev/null` 2>/dev/null || true
  endscript
}
