-- This file was created by create_static_uris.py automatically, do NOT modify it.

local staticPages = {
    
    ["/wifikeyboard"] = "wifikeyboard.html",
    ["/wifi-keyboard_header"] = "wifi-keyboard_header.html",
    ["/contactus"] = "contactus.html",
    ["/minilyrics/default"] = "minilyrics/default.html",
    ["/minilyrics/"] = "minilyrics/default.html",
    ["/minilyrics/buy_lifetime"] = "minilyrics/buy_lifetime.html",
    ["/minilyrics/buy"] = "minilyrics/buy.html",
    ["/minilyrics/faq"] = "minilyrics/faq.html",
    ["/minilyrics/send_mail"] = "minilyrics/send_mail.html",
    ["/minilyrics/contactus_form"] = "minilyrics/contactus_form.html",
    ["/minilyrics/faq/MediaMonkey-lyrics"] = "minilyrics/faq/MediaMonkey-lyrics.html",
    ["/minilyrics/faq/XMPlay-lyrics"] = "minilyrics/faq/XMPlay-lyrics.html",
    ["/minilyrics/faq/install"] = "minilyrics/faq/install.html",
    ["/minilyrics/faq/Windows-Media-Player-lyrics"] = "minilyrics/faq/Windows-Media-Player-lyrics.html",
    ["/minilyrics/faq/lyricsinplayer"] = "minilyrics/faq/lyricsinplayer.html",
    ["/minilyrics/faq/lyrscrollaction"] = "minilyrics/faq/lyrscrollaction.html",
    ["/minilyrics/faq/find-code"] = "minilyrics/faq/find-code.html",
    ["/minilyrics/faq/default"] = "minilyrics/faq/default.html",
    ["/minilyrics/faq/"] = "minilyrics/faq/default.html",
    ["/minilyrics/faq/players"] = "minilyrics/faq/players.html",
    ["/minilyrics/faq/search-lyrics-suggestions"] = "minilyrics/faq/search-lyrics-suggestions.html",
    ["/minilyrics/faq/Winamp-lyrics"] = "minilyrics/faq/Winamp-lyrics.html",
    ["/minilyrics/faq/editlrc"] = "minilyrics/faq/editlrc.html",
    ["/minilyrics/faq/loadembeddedlyrics"] = "minilyrics/faq/loadembeddedlyrics.html",
    ["/minilyrics/faq/foobar2000-lyrics"] = "minilyrics/faq/foobar2000-lyrics.html",
    ["/minilyrics/faq/MusicBee-lyrics"] = "minilyrics/faq/MusicBee-lyrics.html",
    ["/minilyrics/faq/leadsinger"] = "minilyrics/faq/leadsinger.html",
    ["/minilyrics/faq/iPod-Lyrics-Downloader"] = "minilyrics/faq/iPod-Lyrics-Downloader.html",
    ["/minilyrics/faq/disable"] = "minilyrics/faq/disable.html",
    ["/minilyrics/faq/ineterror"] = "minilyrics/faq/ineterror.html",
    ["/minilyrics/faq/vlc-lyrics"] = "minilyrics/faq/vlc-lyrics.html",
    ["/minilyrics/faq/logitech-lcd"] = "minilyrics/faq/logitech-lcd.html",
    ["/minilyrics/faq/uninstall"] = "minilyrics/faq/uninstall.html",
    ["/minilyrics/faq/embedlyrics"] = "minilyrics/faq/embedlyrics.html",
    ["/minilyrics/faq/Spotify-lyrics"] = "minilyrics/faq/Spotify-lyrics.html",
    ["/minilyrics/faq/premium-feedback"] = "minilyrics/faq/premium-feedback.html",
    ["/minilyrics/faq/firewall"] = "minilyrics/faq/firewall.html",
    ["/minilyrics/faq/iTunes-lyrics"] = "minilyrics/faq/iTunes-lyrics.html",
    ["/minilyrics/faq/wmp"] = "minilyrics/faq/wmp.html",
    ["/minilyrics/faq/lyrics"] = "minilyrics/faq/lyrics.html",
    ["/minilyrics/faq/upload"] = "minilyrics/faq/upload.html",
    ["/minilyrics/faq/preference-lyrics-download"] = "minilyrics/faq/preference-lyrics-download.html",
    ["/minilyrics/faq/setting-files"] = "minilyrics/faq/setting-files.html",
    ["/minilyrics/download/languagecode"] = "minilyrics/download/languagecode.html",
    ["/minilyrics/download/default"] = "minilyrics/download/default.html",
    ["/minilyrics/download/"] = "minilyrics/download/default.html",
    ["/minilyrics/download/mlwhatsnew"] = "minilyrics/download/mlwhatsnew.html",
    ["/minilyrics/download/mac"] = "minilyrics/download/mac.html",
    ["/minilyrics/download/skins"] = "minilyrics/download/skins.html",
    ["/minilyrics/download/older"] = "minilyrics/download/older.html",
    ["/minilyrics/download/lyrics_output_plugins"] = "minilyrics/download/lyrics_output_plugins.html",
    ["/minilyrics/download/android"] = "minilyrics/download/android.html",
    ["/minilyrics/download/languages"] = "minilyrics/download/languages.html",
    ["/minilyrics/download/localize"] = "minilyrics/download/localize.html",
}

return staticPages
